vars:
  - id: pip-args
    value: --quiet --upgrade
jobs:
  - id: lint
    help: Run linting
    run: [format, ruff]
  - id: format
    help: Run the black formatter
    run: black
    args: ["."]
  - id: ruff
    help: Run the ruff linter
    run: ruff
    args: ["--fix", "."]
  - id: test
    help: Run unit tests
    run: pytest
  - id: check
    help: Run CI/CD checks
    run: [lint, test]
  - id: upgrade-pip
    help: Upgrade pip version
    run: pip
    args: ["install", "${pip-args}", "pip"]
