vars:
  - id: pip-args
    value: --quiet --upgrade
jobs:
  - id: lint
    jobs:
      - id: format
        run: black
        args: ["."]
      - id: ruff
        run: ruff
        args: ["--fix", "."]
  - id: test
    run: pytest
  - id: check
    run: [lint, test]
  - id: upgrade-pip
    run: pip
    args: ["install", "${pip-args}", "pip"]
